In [1]:
import pandas as pd

In [9]:
pred_df = pd.read_csv('part_of_speech_estimated.csv', index_col=0)
pred_df

             word                            pred   entropy
4834            -                             NaN  0.000000
8660            ą                             NaN  0.000000
4832            -                             NaN  0.000000
4833            -                             NaN  0.000000
4835            -                             NaN  0.000000
...           ...                             ...       ...
3360   tuiʔtù:rá:  GLOSS_START;PARTICLE;GLOSS_END  2.231133
11630  tuʔatí:reʔ      GLOSS_START;VERB;GLOSS_END  2.231708
186     i:nǫ́:šeʔ  GLOSS_START;PARTICLE;GLOSS_END  2.232699
3494     dàʔúʔrah  GLOSS_START;PARTICLE;GLOSS_END  2.233202
12623     dudáʔwa      GLOSS_START;VERB;GLOSS_END  2.234130

[12661 rows x 3 columns]

In [8]:
label_df = pd.read_csv('datasets/wyandot words/labeled.tsv', sep='\t', index_col=0)
label_df

                 word                      morphology
10444       tatęríʔah       GLOSS_START;UNK;GLOSS_END
6225        yatù:yę́h      GLOSS_START;VERB;GLOSS_END
4743         hę̀haǫ́ʔ      GLOSS_START;VERB;GLOSS_END
7408   túhaʔgyę́ʔšraʔ      GLOSS_START;VERB;GLOSS_END
591          duwé:heʔ      GLOSS_START;VERB;GLOSS_END
...               ...                             ...
717           té:reʔs      GLOSS_START;VERB;GLOSS_END
5369        yadú:šraʔ      GLOSS_START;NOUN;GLOSS_END
12657         ęʔtrǫ́ʔ  GLOSS_START;PARTICLE;GLOSS_END
10512      di:wì:nǫ́h      GLOSS_START;VERB;GLOSS_END
5039       di:wì:nǫ́h      GLOSS_START;VERB;GLOSS_END

[157 rows x 2 columns]

In [12]:
og_df = pd.read_csv('tn_words_tabular.tsv', sep='\t', index_col=0)
og_df

,word,gloss,word_barbeau,reference,english_context
0,hǫtèʔyęʔá:ha:,they.are.brothers.and.sister,ho;^te`>3yE;^>a;'.ha;.,TN:01:059:01-02,Several brothers and sisters were living toget...
1,hatidá:reʔ,they.live.[together],ha^tI8da'.re>,TN:01:059:01-02,Several brothers and sisters were living toget...
2,aʔtemę́tayeh,every.day,a>te^mE;'taye<,TN:01:059:03-06,The only meal they had every day consisted of ...
3,tuhą́ʔrąʔ,that.is.all,tu^ha;'>2ra;>,TN:01:059:03-06,The only meal they had every day consisted of ...
4,dekyéhša,that.they.use.all,"de^k,e'<ca",TN:01:059:03-06,The only meal they had every day consisted of ...
...,...,...,...,...,...
12656,wádat,villagers.(Wyandots),wa;'8da^t,TN:38:304:12-17,had fought against only nine Wyandots [and had...
12657,ęʔtrǫ́ʔ,nine,E;>9tro;'>6,TN:38:304:12-17,had fought against only nine Wyandots [and had...
12658,naǫ̀daéʔ,of.them,nao;`8daE'>,TN:38:304:12-17,had fought against only nine Wyandots [and had...
12659,ihę́:nǫh,that.many,ivhE;'.no;<,TN:38:304:12-17,had fought against only nine Wyandots [and had...
12660,deh,r,š,TN:39:307:09-10,ǫ m à h šut á : ʔah de<cro;^ma;`<cu^ta'.>a< th...

In [14]:
preds = pd.concat([label_df, pred_df.rename({'pred': 'morphology'}, axis=1)])
preds

                 word                      morphology   entropy
10444       tatęríʔah       GLOSS_START;UNK;GLOSS_END       NaN
6225        yatù:yę́h      GLOSS_START;VERB;GLOSS_END       NaN
4743         hę̀haǫ́ʔ      GLOSS_START;VERB;GLOSS_END       NaN
7408   túhaʔgyę́ʔšraʔ      GLOSS_START;VERB;GLOSS_END       NaN
591          duwé:heʔ      GLOSS_START;VERB;GLOSS_END       NaN
...               ...                             ...       ...
3360       tuiʔtù:rá:  GLOSS_START;PARTICLE;GLOSS_END  2.231133
11630      tuʔatí:reʔ      GLOSS_START;VERB;GLOSS_END  2.231708
186         i:nǫ́:šeʔ  GLOSS_START;PARTICLE;GLOSS_END  2.232699
3494         dàʔúʔrah  GLOSS_START;PARTICLE;GLOSS_END  2.233202
12623         dudáʔwa      GLOSS_START;VERB;GLOSS_END  2.234130

[12818 rows x 3 columns]

In [15]:
og_df.join(preds.loc[:, 'morphology'])

,word,gloss,word_barbeau,reference,english_context,morphology
0,hǫtèʔyęʔá:ha:,they.are.brothers.and.sister,ho;^te`>3yE;^>a;'.ha;.,TN:01:059:01-02,Several brothers and sisters were living toget...,GLOSS_START;VERB;GLOSS_END
1,hatidá:reʔ,they.live.[together],ha^tI8da'.re>,TN:01:059:01-02,Several brothers and sisters were living toget...,GLOSS_START;VERB;GLOSS_END
2,aʔtemę́tayeh,every.day,a>te^mE;'taye<,TN:01:059:03-06,The only meal they had every day consisted of ...,GLOSS_START;VERB;GLOSS_END
3,tuhą́ʔrąʔ,that.is.all,tu^ha;'>2ra;>,TN:01:059:03-06,The only meal they had every day consisted of ...,GLOSS_START;PARTICLE;GLOSS_END
4,dekyéhša,that.they.use.all,"de^k,e'<ca",TN:01:059:03-06,The only meal they had every day consisted of ...,GLOSS_START;VERB;GLOSS_END
...,...,...,...,...,...,...
12657,ęʔtrǫ́ʔ,nine,E;>9tro;'>6,TN:38:304:12-17,had fought against only nine Wyandots [and had...,GLOSS_START;PARTICLE;GLOSS_END
12657,ęʔtrǫ́ʔ,nine,E;>9tro;'>6,TN:38:304:12-17,had fought against only nine Wyandots [and had...,GLOSS_START;PARTICLE;GLOSS_END
12658,naǫ̀daéʔ,of.them,nao;`8daE'>,TN:38:304:12-17,had fought against only nine Wyandots [and had...,GLOSS_START;PARTICLE;GLOSS_END
12659,ihę́:nǫh,that.many,ivhE;'.no;<,TN:38:304:12-17,had fought against only nine Wyandots [and had...,GLOSS_START;VERB;GLOSS_END
12660,deh,r,š,TN:39:307:09-10,ǫ m à h šut á : ʔah de<cro;^ma;`<cu^ta'.>a< th...,GLOSS_START;PARTICLE;GLOSS_END

In [18]:
verbs_df = og_df.join(preds.loc[:, 'morphology'])
verbs_df = verbs_df[~verbs_df.morphology.isna()]
mask = verbs_df.morphology.apply(lambda x: 'VERB' in x)
verbs_df = verbs_df[mask]
verbs_df

,word,gloss,word_barbeau,reference,english_context,morphology
0,hǫtèʔyęʔá:ha:,they.are.brothers.and.sister,ho;^te`>3yE;^>a;'.ha;.,TN:01:059:01-02,Several brothers and sisters were living toget...,GLOSS_START;VERB;GLOSS_END
1,hatidá:reʔ,they.live.[together],ha^tI8da'.re>,TN:01:059:01-02,Several brothers and sisters were living toget...,GLOSS_START;VERB;GLOSS_END
2,aʔtemę́tayeh,every.day,a>te^mE;'taye<,TN:01:059:03-06,The only meal they had every day consisted of ...,GLOSS_START;VERB;GLOSS_END
4,dekyéhša,that.they.use.all,"de^k,e'<ca",TN:01:059:03-06,The only meal they had every day consisted of ...,GLOSS_START;VERB;GLOSS_END
5,dehskát,this.one.[meal],dE<ska't,TN:01:059:03-06,The only meal they had every day consisted of ...,GLOSS_START;VERB;GLOSS_END
...,...,...,...,...,...,...
12647,sahǫ̀:trí:žuʔ,again:they.fought,"sa^ho;`.tri"".ju>",TN:37:299:20-26,"From that time on, the fight became incessant ...",GLOSS_START;VERB;GLOSS_END
12649,ahútì:du:rǫʔ,they.are.tired.(of.it),a^hu^/ti~.du.ro;>,TN:37:299:20-26,"From that time on, the fight became incessant ...",GLOSS_START;VERB;GLOSS_END
12651,wà:dát,villagers,wa;`.nda^/t,TN:37:299:20-26,"From that time on, the fight became incessant ...",GLOSS_START;VERB;GLOSS_END
12656,wádat,villagers.(Wyandots),wa;'8da^t,TN:38:304:12-17,had fought against only nine Wyandots [and had...,GLOSS_START;VERB;GLOSS_END
12659,ihę́:nǫh,that.many,ivhE;'.no;<,TN:38:304:12-17,had fought against only nine Wyandots [and had...,GLOSS_START;VERB;GLOSS_END

In [19]:
verbs_df.to_csv('wyandot_verbs.tsv', sep='\t')